### ISSUE TITLE
`generate_arcs` function

### ISSUE THREAD

**Issue by rogerkuou** [MotionbyLearning/DePSI#16]
Create a function to generate arcs of a network from an STM.

```python
import xarray as xr
from pydepsi.network import generate_arcs

stm_points = xr.open_zarr(`exmaple_stm.zarr`)

stm_arcs = generate_arcs(stm_points, method='delaunay')
```

```python
def generate_arcs(stm_points, method='delaunay', min_length=50, max_length=1000, x='lon', y='lat'):
  pass
```

args:
- `stm_points`: input Space-Time Matrix in form of Xarray.Dataset.
- `method`: ways to form the network"delaunay" or "redundant"
- `min_length`/`max_length`: min/max length of the generated arc
- `x`/`y`: horizontal coordinates used to calculate the arcs

return
- `stm_arcs`: An STM in form of Xarray.Dataset, with each element in space an arc. Three data variables: 
    - start_idx (space): index of starting point in  `stm_points`
    - end_idx (space): index of end point in  `stm_points`
    - diff_phase (sapce): phase diffencese `end['phase'] - start['phase']`

For delauney implementation, consider this one from [`scipy`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.Delaunay.html)

Freek will provide the current implementation of redundant in MATLAB:
- https://bitbucket.org/grsradartudelft/depsi/src/master/main/ps_form_network.m
- https://bitbucket.org/grsradartudelft/depsi/src/master/main/ps_construct_redundant_network.m

Example notebook of retrieving and sparsing a STM:
[network.zip](https://github.com/user-attachments/files/17011970/network.zip)

**Comment by FreekvanLeijen** [comment]
@vanlankveldthijs You can find descriptions of the existing Matlab implementations in my thesis, see

https://resolver.tudelft.nl/uuid:5dba48d7-ee26-4449-b674-caa8df93e71e

Networks: page 50.
Overall processing flow, see page 31.

**Comment by FreekvanLeijen** [comment]
@vanlankveldthijs As discussed, I realized that the Delaunay triangulation is also used in another function, where it is used to create a set of short, independent arcs between points. (Max 1 arc per point, not all points need to be used necessarily.)

See https://bitbucket.org/grsradartudelft/depsi/src/master/main/ps_vce.m

It would be nice if the (scipy) Delaunay function we are going to use, enables the same functionality (that is, provides the indices etc needed. But I guess it will.)

**Comment by vanlankveldthijs** [comment]
We decided not to add any attributes to the arcs. These can be collected from the points referenced.
