### ISSUE TITLE
`sparse_selection` function

### ISSUE THREAD

**Issue by rogerkuou** [MotionbyLearning/DePSI#17]
Given a STM, make a subset with `min_dist` arg. Every two entries of the output STM should have at least the `min_dist` distance.

The results will be used for #16.

**Comment by FreekvanLeijen** [comment]
Hi Ou,
I actually ended up creating a working Matlab script, see attachment.

[pseudocode_sparsify.txt](https://github.com/user-attachments/files/17259727/pseudocode_sparsify.txt)

The iterative calculation of the distances with the hypot function is the most expensive operation, I guess. Optimization is possible I guess, e.g. by selection of the points around the middle point in the bounding box around it.
